image: Visual Studio 2017
platform: x64
shallow_clone: true
skip_tags: true
environment:
  matrix:
    -
      nodejs_version: Stable
      npm_version: '6.0.1'
      another_npm_version: '6.0.0'
      COVERALLS_REPO_TOKEN:
        secure: KeN37NXWmMhEHWGb0U4ZbtVf+CgmcdLts/HmKS6yRqDI6WNflrSyjgXwXy3HR2Oe
      COVERALLS_SERVICE_NAME: AppVeyor
      COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
      COVERALLS_GIT_BRANCH: '%APPVEYOR_REPO_BRANCH%'
      COVERALLS_GIT_COMMIT: '%APPVEYOR_REPO_COMMIT%'
    -
      nodejs_version: LTS
      npm_version: '5.8.0'
      another_npm_version: '5.8.0-next.0'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - 'npm --version # Original npm version'
  - npm install --global npm@%npm_version%
  - set PATH=%APPDATA%\npm;%PATH%
  - 'npm --version # User-installed npm version'
  - npm ci
matrix:
  fast_finish: true
build: off
test_script:
  - npx nyc node tests\non-windows.js
  - npx nyc node tests\no-npm.js
  - npm config get prefix --global
  - npx nyc node tests\has-user-npm.js
  - npm config set prefix --global tmp
  - npm config get prefix --global
  - npx nyc node tests\no-user-npm.js
  - npm install --global npm@%another_npm_version%
  - npx nyc node tests\customized-npm-prefix.js
  - npx nyc node tests\broken-cli-file.js
on_success:
  - npx nyc report --reporter=text
  - ps: If ($env:COVERALLS_REPO_TOKEN) {npx nyc report --reporter=text-lcov | npx --quiet coveralls}
