shallow_clone: true
version: '{build}'
skip_tags: true
environment:
  matrix:
    -
      nodejs_version: Stable
      npm_version: '3.10.0'
      another_npm_version: '3.9.6'
      COVERALLS_REPO_TOKEN:
        secure: KeN37NXWmMhEHWGb0U4ZbtVf+CgmcdLts/HmKS6yRqDI6WNflrSyjgXwXy3HR2Oe
      COVERALLS_SERVICE_NAME: AppVeyor
      COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
      COVERALLS_GIT_BRANCH: '%APPVEYOR_REPO_BRANCH%'
      COVERALLS_GIT_COMMIT: '%APPVEYOR_REPO_COMMIT%'
    -
      nodejs_version: LTS
      npm_version: '2.15.7'
      another_npm_version: '2.15.5'
install:
  - ps: Install-Product node $env:nodejs_version
  - 'npm --version # Original npm version'
  - npm install --global npm@%npm_version%
  - set PATH=%APPDATA%\npm;%PATH%
  - 'npm --version # User-installed npm version'
  - npm uninstall --save-dev @shinnn/eslint-config-node-legacy eslint
  - npm install
matrix:
  fast_finish: true
build: off
test_script:
  - node node_modules\istanbul\lib\cli.js cover --dir=cov0 tests\non-windows.js
  - node node_modules\istanbul\lib\cli.js cover --dir=cov1 tests\no-npm.js
  - npm config get prefix --global
  - node node_modules\istanbul\lib\cli.js cover --dir=cov2 tests\has-user-npm.js
  - npm config set prefix --global tmp
  - npm config get prefix --global
  - node node_modules\istanbul\lib\cli.js cover --dir=cov3 tests\no-user-npm.js
  - npm install --global npm@%another_npm_version%
  - node node_modules\istanbul\lib\cli.js cover --dir=cov4 tests\customized-npm-prefix.js
  - node node_modules\istanbul\lib\cli.js cover --dir=cov5 tests\broken-cli-file.js
on_success:
  - ps: If ($env:COVERALLS_REPO_TOKEN) {Invoke-Expression 'npm run-script coveralls'}
cache: node_modules -> package.json
